/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SolanaRouteImport } from './routes/solana/route'
import { Route as SolanaIndexImport } from './routes/solana/index'

// Create/Update Routes

const SolanaRouteRoute = SolanaRouteImport.update({
  id: '/solana',
  path: '/solana',
  getParentRoute: () => rootRoute,
} as any)

const SolanaIndexRoute = SolanaIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolanaRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solana': {
      id: '/solana'
      path: '/solana'
      fullPath: '/solana'
      preLoaderRoute: typeof SolanaRouteImport
      parentRoute: typeof rootRoute
    }
    '/solana/': {
      id: '/solana/'
      path: '/'
      fullPath: '/solana/'
      preLoaderRoute: typeof SolanaIndexImport
      parentRoute: typeof SolanaRouteImport
    }
  }
}

// Create and export the route tree

interface SolanaRouteRouteChildren {
  SolanaIndexRoute: typeof SolanaIndexRoute
}

const SolanaRouteRouteChildren: SolanaRouteRouteChildren = {
  SolanaIndexRoute: SolanaIndexRoute,
}

const SolanaRouteRouteWithChildren = SolanaRouteRoute._addFileChildren(
  SolanaRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/solana': typeof SolanaRouteRouteWithChildren
  '/solana/': typeof SolanaIndexRoute
}

export interface FileRoutesByTo {
  '/solana': typeof SolanaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/solana': typeof SolanaRouteRouteWithChildren
  '/solana/': typeof SolanaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/solana' | '/solana/'
  fileRoutesByTo: FileRoutesByTo
  to: '/solana'
  id: '__root__' | '/solana' | '/solana/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SolanaRouteRoute: typeof SolanaRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  SolanaRouteRoute: SolanaRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/solana"
      ]
    },
    "/solana": {
      "filePath": "solana/route.tsx",
      "children": [
        "/solana/"
      ]
    },
    "/solana/": {
      "filePath": "solana/index.tsx",
      "parent": "/solana"
    }
  }
}
ROUTE_MANIFEST_END */
